<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
    <!-- Caster Wheel Link -->
    <link name="caster_wheel_link">
      <visual>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_sphere>
    </link>

    <link name="caster2_wheel_link">
      <visual>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_sphere>
    </link>

    <joint name="caster_wheel2_joint" type="fixed">
      <origin xyz="${-caster_wheel_offset_x} 0.0 ${caster_wheel_offset_z}" rpy="0.0 0.0 0.0"/>
      <parent link="chassis_link"/>
      <child link="caster2_wheel_link"/>
    </joint>

    <link name="caster2_holder">
      <visual>
        <geometry>
          <cylinder radius="${caster_wheel_radius/2}" length="${caster_wheel_offset_z*2}"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>
  
    <!-- Holder Joint -->
    <joint name="holder2_joint" type="fixed">
      <origin xyz="${-caster_wheel_offset_x} 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <parent link="chassis_link"/>
      <child link="caster2_holder"/>
    </joint>





  
    <!-- Caster Wheel Joint -->
    <joint name="caster_wheel_joint" type="fixed">
      <origin xyz="${caster_wheel_offset_x} 0.0 ${caster_wheel_offset_z}" rpy="0.0 0.0 0.0"/>
      <parent link="chassis_link"/>
      <child link="caster_wheel_link"/>
    </joint>
  
    <!-- Caster Holder (Only for visuals) -->
    <link name="caster_holder">
      <visual>
        <geometry>
          <cylinder radius="${caster_wheel_radius/2}" length="${caster_wheel_offset_z*2}"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>
  
    <!-- Holder Joint -->
    <joint name="holder_joint" type="fixed">
      <origin xyz="${caster_wheel_offset_x} 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <parent link="chassis_link"/>
      <child link="caster_holder"/>
    </joint>
  
  </robot>
  